project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: "#ccccff"

    left:
    - text: "Hands-on Exercise"
      menu:
      - text: Week 1&2
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
      - text: Week 3
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
  
      - text: Week 4
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd"
    
    - text: "In-class Exercise"
      menu:
      - text: In-class Exercise 2
        href: "In-class_Ex/In-class_Ex02/In-class_Ex02.qmd"
      - text: In-class Exercise 3
        href: "In-class_Ex/In-class_Ex03/In-class_Ex03.qmd"
      - text: In-class Exercise 4
        href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"
        
    - text: "Take-home assignment"
      menu:
      - text: Take-home assignment 1 
        href: "Take-home_Assgn/Take-home_Assgn1/Take-home_Assgn1.qmd"

    
    
    right:
      - href: home.qmd
        text: Home
        
      - href: about.qmd
        text: About
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

