project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: "#7D0541"

    left:
    - text: "Hands-on Exercise"
      menu:
      - text: Week 1&2
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
      - text: Week 3
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
      - text: Week 4
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd"
      - text: Week 5
        href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd"
      - text: Week 6
        href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd"
      - text: Week 7
        href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd"
      - text: Week 8
        href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd"
    
    - text: "In-class Exercise"
      menu:
      - text: In-class Exercise 2
        href: "In-class_Ex/In-class_Ex02/In-class_Ex02.qmd"
      - text: In-class Exercise 3
        href: "In-class_Ex/In-class_Ex03/In-class_Ex03.qmd"
      - text: In-class Exercise 4
        href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"
      - text: In-class Exercise 5
        href: "In-class_Ex/In-class_Ex05/In-class_Ex05.qmd"
      - text: In-class Exercise 6
        href: "In-class_Ex/In-class_Ex06/In-class_Ex06.qmd"
      - text: In-class Exercise 7
        href: "In-class_Ex/In-class_Ex07/In-class_Ex07.qmd"
      - text: In-class Exercise 8
        href: "In-class_Ex/In-class_Ex08/In-class_Ex08.qmd"
      - text: In-class Exercise 9
        href: "In-class_Ex/In-class_Ex09/In-class_Ex09.qmd"
      - text: In-class Exercise 10
        href: "In-class_Ex/In-class_Ex10/In-class_Ex10.qmd"
      - text: In-class Exercise 11
        href: "In-class_Ex/In-class_Ex11/In-class_Ex11.qmd"
        
    - text: "Take-home Assignment"
      menu:
      - text: Take-home Assignment 1 
        href: "Take-home_Assgn/Take-home_Assgn1/Take-home_Assgn1.qmd"
      - text: Take-home Assignment 2
        href: "Take-home_Assgn/Take-home_Assgn2/Take-home_Assgn2.qmd"
      - text: Take-home Assignment 3
        href: "Take-home_Assgn/Take-home_Assgn3/Take-home_Assgn3.qmd"

    
    
    #right:
    #  - href: index.qmd
    #    text: Home
        
    #  - href: about.qmd
    #    text: About
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

