---
title: "Hands-on Ex 6:"

title-block-banner: true

date: "6 february 2023" 
date-modified: last-modified 
author: "Rhonda Ho Kah Yee"

format: 
  html: 
    code-fold: true 
    code-tools: true

execute: 
  message: false 
  warning: false 
  eval: false

editor: visual
---

# Spatial Weights and Applications

## Loading of Packages
```{r}

pacman::p_load(sf, sfdep, tmap, tidyverse, knitr)

#inclass uses sfdep, handson uses spdep
```

## Getting the Data Into R Environment

Importing shapefile into r environment
```{r}
# st_read from sf package 

# task: make it into sf df
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") 

# %>% st_transform(crs = 4490)


```
Import csv file into r environment
```{r}

#tibble df
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
#head(hunan,5) colnames(hunan2012)

```

Performing relational join
```{r}
# left join-> missing a unique identifier but it automatically matches county

hunan_GDPC <- left_join(hunan,hunan2012)%>%
  select(1:4, 7, 15)
```



```{r}
tmap_mode("plot")
tm_shape (hunan_GDPC) + 
  tm_fill("GDPPC",
          style = "quantile",
          palette = "Blues",
          title = "GDPPC") +
tm_layout ( main.title = "Distribution of GDP per capita by distribution",
            main.title.position = "center",
            main.title.size = 1.2,
            legend.height = 0.45,
            legend.width = 0.35,
            frame = TRUE) +
tm_borders (alpha = 0.5) +
tm_compass (type="8star", size = 2) +
tm_scale_bar() + 
tm_grid(alpha =0.2)

# tmap auto changes from decimal to kilometres using great circle formula

```

```{r}

cn_queen <- hunan_GDPC %>%
  mutate(nb= st_contiguity(geometry),
         .before=1)
```

```{r}

```


