---
title: "In-class Ex 8"

title-block-banner: true

date: "6 march 2023" 
date-modified: last-modified 
author: "Rhonda Ho Kah Yee"

format: 
  html: 
    code-fold: true 
    code-tools: true

execute: 
  message: false 
  warning: false 
  eval: false

editor: visual
---

Notes on takehome ex2

```{r}
# timeline map should make 1 legend outside

#increase fig width
#| fig-width: 10
```

# Getting Started

```{r}
pacman::p_load(readr,dplyr,vctrs, olsrr, corrplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary)

#for corrplot, advised not to load it in first and to install seperately as it has conflicts with tidyverse  

# when needed can write like this
#corrplot::corrplot(cor(condo_resale[, 5:23]), diag = FALSE, order = "AOE",
#         tl.pos = "td", tl.cex = 0.5, method = "number", type = "upper")

# but i added readr,dplyr,vctrs to resolve the loading issue during the handson ex
```

# Importing the Data

## Geospatial Data

```{r}
mpsz = st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE_WEB_PL")

#update crs
mpsz_svy21 <- st_transform(mpsz, 3414)

st_bbox(mpsz_svy21) #view extent
```

## Aspatial Data

```{r}
condo_resale = read_csv("data/aspatial/Condo_resale_2015.csv")


```

```{r}
# to check for excessive no. of 0, check the spread to determine whether we can use the variable (cannot use if min median mean ALL 0 or ALL same value)
summary(condo_resale)
```

**Converting aspatial data frame into a sf object**

```{r}
condo_resale.sf <- st_as_sf(condo_resale,
                            coords = c("LONGITUDE", "LATITUDE"),
                            crs=4326) %>%
  st_transform(crs=3414)
```

Save entire model into condo.mlr . Note that condo.mlr is an lm object (contains all impt variables for least square model).

```{r}
condo.mlr <- lm(formula = SELLING_PRICE ~ AREA_SQM + AGE    + 
                  PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +
                  PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + PROX_KINDERGARTEN + 
                  PROX_MRT  + PROX_PARK + PROX_PRIMARY_SCH + 
                  PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + 
                  PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
                data=condo_resale.sf)
summary(condo.mlr)
```
